[package]
name = "chapter01-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bench]]
name = "performance"
harness = false