[package]
name = "performance_comparison"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "memory_benchmark"
harness = false

[[bin]]
name = "benchmark"
path = "src/benchmark.rs"